apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        version: green
    spec:
      containers:
      - name: my-app-container
        image: nandanajsreenivas/my-blue-green-app:initial # Placeholder image
        ports:
        - containerPort: 8080