apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30008 # Using a new port to avoid conflicts
  selector:
    app: my-app
    version: blue # Initially, directs traffic to the blue deployment